config/routes.rb
Timely::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  # devise_for :users

  post '/api_call' => 'home#api_call'
  get '/api_call' => 'home#api_call'

  get '/keywords' => 'user#user_keywords'
  delete '/keywords/:id' => 'user#keyword_destroy'
  post '/keywords' => 'user#keyword_create'

  get '/user/preferences' => 'user#preferences', as: 'edit_user_preferences'
  get '/user/id' => 'user#user_id'

  get '/map_reference' => 'home#google_api'

  root to: 'home#index'

  get '/scooterTest' => 'home#scooterTest'

  resources :keywords
  # used to initialize first users


end

app/models/dislike.rb
class Dislike < ActiveRecord::Base
  attr_accessible :address, :disliked_date, :name, :rating, :url, :user_id

  belongs_to :user

  # RATINGS = ["★", "★★", "★★★", "★★★★", "★★★★★"]

end

app/models/keyword.rb
class Keyword < ActiveRecord::Base
  attr_accessible :keyword, :period_of_time, :user_id

  belongs_to :users

end

app/models/like.rb
class Like < ActiveRecord::Base
  attr_accessible :address, :liked_date, :name, :rating, :url, :user_id

  belongs_to :user

  # RATINGS = ["★", "★★", "★★★", "★★★★", "★★★★★"]

end

app/models/period_of_time_definitions.rb
class PeriodOfTimeDefinitions < ActiveRecord::Base
  attr_accessible :afternoon, :evening, :morning, :night, :noon, :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  # Custom Items
  attr_accessible :name

  has_many :dislikes, :dependent => :destroy
  has_many :likes, :dependent => :destroy
  
  has_many :keywords, :dependent => :destroy
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
require 'yelp_api' # in the lib/assets folder
require 'get_keyword' # in the lib/assets folder

class HomeController < ApplicationController

  def index
  	
  end

  def google_api
    google_api_key = ENV["GOOGLE_API_KEY"]

    @key = {key: google_api_key}

    render json: @key

  end

  def api_call
    latitude   = params[:latitude].to_f
    longitude  = params[:longitude].to_f
    local_time = params[:local_time].to_i
    keywords = get_keywords(local_time, current_user)

    @results = lat_lon_keyword_search(latitude, longitude, keywords)

    render json: @results

  end

  def scooterTest
  	latitude = 40.740091899999996
    longitude = -73.98969
    @results = lat_lon_keyword_search(latitude, longitude, ["bagels","coffee"])

  end

	#NOTE: THERE IS NO ROUTE FOR THIS METHOD
	def zipsearch(inZipcode)
		return YelpApi.searchZip(inZipcode)
	end

	#NOTE: THERE IS NO ROUTE FOR THIS METHOD
	# Call this method with the Latitude, Longitude
	# and an array of keywords eg ["dinner", "chinese"]
	#40, -70 -- this returns an error that I should handle
	def lat_lon_keyword_search(inLat, inLon, inKeywords)
		return YelpApi.searchLatLonKeywords(inLat, inLon, inKeywords)
	end

  def get_keywords(local_time, current_user)
  	return GetKeyword.get_keywords(local_time, current_user)
  end






end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def new
    super
  end

  def create
  	super

    if current_user
    	UserMailer.greetings(current_user).deliver
    	
  		morning = ["breakfast", "bagel", "coffee"]
  		noon = ["lunch", "burgers", "salads"]
  		afternoon = ["coffee", "tea", "crumpets", "petit fours"]
  		evening = ["dinner", "steak", "thai", "mexican"]
  		night = ["bars", "clubs", "dancing", "nightlife"]
  		# time_options = [morning, noon, afternoon, evening, night]
  		# time_of_day = ["morning", "noon", "afternoon", "evening", "night"]


  			morning.each {|item|
  				Keyword.create!(
  					keyword: item,
  					period_of_time: "morning",
  					user_id: current_user.id
  					)
  			}


  			noon.each {|item|
  				Keyword.create!(
  					keyword: item,
  					period_of_time: "noon",
  					user_id: current_user.id
  					)
  			}

  			afternoon.each {|item|
  				Keyword.create!(
  					keyword: item,
  					period_of_time: "afternoon",
  					user_id: current_user.id
  					)
  			}

  			evening.each {|item|
  				Keyword.create!(
  					keyword: item,
  					period_of_time: "evening",
  					user_id: current_user.id
  					)
  			}

  			night.each {|item|
  				Keyword.create!(
  					keyword: item,
  					period_of_time: "night",
  					user_id: current_user.id
  					)
  			}
      end

  end

  def update
    super
  end
end 

app/controllers/user_controller.rb
class UserController < ApplicationController

  def preferences
    
  end

  def user_keywords
    @morning = Keyword.find_all_by_period_of_time_and_user_id('morning',current_user.id)
    @noon = Keyword.find_all_by_period_of_time_and_user_id('noon',current_user.id)
    @afternoon = Keyword.find_all_by_period_of_time_and_user_id('afternoon',current_user.id)
    @evening = Keyword.find_all_by_period_of_time_and_user_id('evening',current_user.id)
    @night = Keyword.find_all_by_period_of_time_and_user_id('night',current_user.id)

    @user_keywords = {
                      morning:    @morning,
                      noon:       @noon,
                      afternoon:  @afternoon,
                      evening:    @evening,
                      night:      @night
                      }

    render json: @user_keywords
  end

  def user_id

    render json: current_user.id

  end

  def keyword_destroy
    keyword_id = params[:id]
    item = Keyword.find(keyword_id)
    item.destroy

    render json: item
  end

  def keyword_create

    word_data = {
                keyword: params[:keyword],
                period_of_time: params[:period_of_time],
                user_id: params[:user_id].to_i
                }


    new_keyword = Keyword.create(word_data)

    render json: new_keyword

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  # A simple way to show error messages for the current devise resource. If you need
  # to customize this method, you can either overwrite it in your application helpers or
  # copy the views to your application.
  #
  # This method is intended to stay simple and it is unlikely that we are going to change
  # it to add more behavior or options.
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation">
      <h3>#{sentence}</h3>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end
end

app/views/home/index.html.erb
<h1 id="device"></h1>

<div id="location"></div>

<div id="main_container">
    <div id="loading_screen"></div>
    <div id="site_container"></div>
</div>

<div class="clearfix green-background">
        <script type="text/javascript">
            $(function() {
                $('#sun_yellow').animate({'top':'96%','opacity':0.4}, 12000,function(){
                    $('#stars').animate({'opacity':1}, 5000,function(){
                        $('#moon').animate({'top':'30%','opacity':1}, 5000, function(){
                            $('#sstar').animate({'opacity':1}, 300);
                            $('#sstar').animate({
                                'backgroundPosition':'0px 0px','top':'15%', 'opacity':0
                            }, 500,function(){
                                // $('#title').animate({'opacity':1}, 1000);
                                $('#back').animate({'opacity':1}, 3000);
                            });
                        });
                    });
                });
                $('#sun_red').animate({'top':'96%','opacity':0.8}, 12000,function(){$('#sun_red').hide();$('#sun_yellow').hide();});
                $('#sky').animate({'backgroundColor':'#4F0030'}, 18000);
                $('#clouds').animate({'backgroundPosition':'1000px 0px','opacity':0}, 30000);

    // $('#stars').animate({'backgroundPosition': '1000px 0px'}, 30000);

                $('#night').animate({'opacity':0.8}, 20000);
            });
        </script>

    <div id="sky"></div>
    <div id="sun_yellow"></div>
    <div id="sun_red"></div>
    <div id="clouds"></div> 
    <div id="ground"></div>
    <div id="night"></div>
    <div id="stars"></div>        
    <div id="sstar"></div>
    <div id="moon"></div> 
    <div id="title"></div>
    <div>
    	<a id="back" href="http://www.tympanus.net/codrops/2009/12/14/day-and-night-creating-animation-with-jquery-and-css/"></a>
    </div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert flash alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Timely" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Timely" %>">
    <link href='http://fonts.googleapis.com/css?family=Playfair+Display' rel='stylesheet' type='text/css'>
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>

 

    <%= csrf_meta_tags %>
  </head>
  <body>

  <header class="navbar navbar-default navbar-static-top" role="banner">
    <div class="container">
      <div class="navbar-header">
        <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href=<%= root_path %>>
          <div class="TimelyLogo">Tim<span><i class="fa fa-clock-o"></i></span>ly</div>
        </a>
      </div>
      <nav class="navbar-collapse bs-navbar-collapse collapse" role="navigation" style="height: 1px;">
        <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li>
            <%= link_to('Edit Account', edit_user_registration_path, method: :get) %>
          </li>
          <li>
            <%= link_to('Edit Preferences', edit_user_preferences_path, method: :get) %>
          </li>
          <li>
            <%= link_to('Sign out', destroy_user_session_path, method: :delete) %>
          </li>
        <% else %>
          <li>
            <%= link_to('Login', new_user_session_path)  %>  
          </li>
        <% end %>
        </ul>
      </nav>
    </div>
  </header>

    <!-- div container class is intitial condition for bootstrap -->
      <div class="container"> 
        <main role="main">
  <!--         <p class="notice flash"><%= notice %></p>
          <p class="alert flash"><%= alert %></p> -->
           <%= render 'layouts/messages' %>
           <%= yield %>
        </main>
      </div>
  </body>
</html>

app/views/user/preferences.html.erb
<h1 style="color: #1F2D54;">Preferences</h1>

<%= @user %>


<!-- Nav tabs -->
<ul class="nav nav-tabs">
  <li id='morningTab' class="active"><a href="#morningContent" data-toggle="tab">Morning</a></li>
  <li id='noonTab' ><a href="#noonContent" data-toggle="tab">Noon</a></li>
  <li id='afternoonTab' ><a href="#afternoonContent" data-toggle="tab">Afternoon</a></li>
  <li id='eveningTab' ><a href="#eveningContent" data-toggle="tab">Evening</a></li>
  <li id='nightTab' ><a href="#nightContent" data-toggle="tab">Night</a></li>
</ul>

<!-- Tab panes -->
<div class="tab-content">

  <div class="tab-pane active" id="morningContent">
    <div class="content-input">
      <input type="text" id="morning_keyword_new" placeholder="Morning Keyword">
      <input type="submit" class="btn btn-default btn-xs" value="Add Keyword">
    </div>
  </div>

  <div class="tab-pane" id="noonContent">
    <div class="content-input">
      <input type="text" id="noon_keyword_new" placeholder="Noon Keyword">
      <input type="submit" class="btn btn-default btn-xs" value="Add Keyword">
    </div>
  </div>

  <div class="tab-pane" id="afternoonContent">
    <div class="content-input">
      <input type="text" id="afternoon_keyword_new" placeholder="Afternoon Keyword">
      <input type="submit" class="btn btn-default btn-xs" value="Add Keyword">
    </div>
  </div>

  <div class="tab-pane" id="eveningContent">
    <div class="content-input">
      <input type="text" id="evening_keyword_new" placeholder="Evening Keyword">
      <input type="submit" class="btn btn-default btn-xs" value="Add Keyword">
    </div>
  </div>

  <div class="tab-pane" id="nightContent">
    <div class="content-input">
      <input type="text" id="night_keyword_new" placeholder="Night Keyword">
      <input type="submit" class="btn btn-default btn-xs" value="Add Keyword">
    </div>
  </div>

</div>